#!/bin/sh
set -e
function usage {
    echo "$0 [ fetch | build | up ]"
}
if [ $# -ne 1 ] ; then
    usage
    exit 2
fi

function fetch {
    raspbian_zip=2014-12-24-wheezy-raspbian.zip
    raspbian_url=http://downloads.raspberrypi.org/raspbian/images/raspbian-2014-12-25/2014-12-24-wheezy-raspbian.zip
    qemu_kernel=https://raw.githubusercontent.com/dhruvvyas90/qemu-rpi-kernel/master/kernel-qemu-3.10.25-wheezy
    pushd resources
    wget $qemu_kernel -O kernel-qemu
    popd
}

function build {
    echo "Copying raspbian image"
    cp resources/*-wheezy-raspbian.img raspbian.img
    # Add 4 GB to end of file
    echo "Growing source image by 4GB"
    dd if=/dev/zero bs=4096 count=1024 >> raspbian.img
    echo "Building image"
    ./raspbian-qemu-expect
    ./expect-raspiconfig
}

function up {
    qemu-system-arm -cpu arm1176 -m 256 -M versatilepb -no-reboot -serial stdio -append "root=/dev/sda2 panic=1 rootfstype=ext4 rw console=ttyAMA0 console=ttyS0" -kernel resources/kernel-qemu -hda raspbian.img -net user,hostfwd=tcp::10022-:22 -net nic
 
}

cmd=$1
case $cmd in
    "fetch")
        fetch
       ;;
    "build")
        build
        ;;
    "up")
        up
       ;;
    *)
        usage
        ;;
esac
