#!/usr/bin/expect -f

spawn qemu-system-arm -cpu arm1176 -m 256 -M versatilepb -no-reboot -serial stdio -append "root=/dev/sda2 panic=1 rootfstype=ext4 rw init=/bin/bash console=ttyAMA0 console=ttyS0" -kernel resources/kernel-qemu -hda raspbian.img

expect "root@(none):/#"
send "sed -i -e s^/usr/lib/arm-linux-gnueabihf/libcofi_rpi.so^#/usr/lib/arm-linux-gnueabihf/libcofi_rpi.so^ /etc/ld.so.preload\n"
expect "root@(none):/#"
send "echo KERNEL==\"sda\", SYMLINK+=\"mmcblk0\" > /etc/udev/rules.d/90-qemu.rules\n"
expect "root@(none):/#"
send "echo KERNEL==\"sda?\", SYMLINK+=\"mmcblk0p%n\" >> /etc/udev/rules.d/90-qemu.rules\n"
expect "root@(none):/#"
send "echo KERNEL==\"sda2\", SYMLINK+=\"root\" >> /etc/udev/rules.d/90-qemu.rules\n"
expect "root@(none):/#"
send "sync"
send "echo ----DONE----\n"
sleep 10
